package org.example.organizatsiondocument

enum class UserRole{
    ADMIN, EMPLOYEE
}

enum class ErrorCodes(val code: Long) {

    USERNAME_ALREADY_EXISTS(103),
    USER_NOT_FOUND(104),
    USER_ALREADY_EXISTS(105),
    PASSWORD_IS_INCORRECT(106),
    NOT_LOGGED_IN_EXCEPTION(107),

    PRODUCT_NAME_ALREADY_EXISTS(200),
    PRODUCT_NOT_FOUND(201),
    PHONE_NUMBER_ALREADY_EXISTS(202),

    ORGANIZATION_NOT_FOUND(203),
    ORGANIZATION_NAME_ALREADY_EXISTS(204),

    MEASUREMENT_UNIT_NAME_ALREADY_EXISTS(205),
    MEASUREMENT_UNIT_NOT_FOUND(206),

    CURRENCY_NAME_ALREADY_EXISTS(207),
    CURRENCY_NOT_FOUND(208),

    SUPPLIER_PHONE_NUMBER_ALREADY_EXISTS(209),
    SUPPLIER_NOT_FOUND(210),

    PENDING_ORDER_NOT_FOUND(300),
    FORBIDDEN(301),
    TEMPLATE_NOT_FOUND(500)
}

